{
  "openapi": "3.0.1",
  "info": {
    "title": "CodeLeap-api",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/careers/{postId}/comments/": {
      "get": {
        "summary": "Comments",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "postId",
            "in": "path",
            "description": "",
            "required": true,
            "example": "3",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "cursor",
            "in": "query",
            "description": "",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "next": {
                      "type": "null"
                    },
                    "previous": {
                      "type": "null"
                    },
                    "results": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  },
                  "required": [
                    "next",
                    "previous",
                    "results"
                  ]
                },
                "example": {
                  "next": null,
                  "previous": null,
                  "results": [
                    {
                      "id": 27,
                      "name": "Rodrigo Oliveira",
                      "username": "rodrigo_123",
                      "content": "this is a good comment @rodrigo_123",
                      "created_datetime": "2025-07-28T21:34:36.317264Z",
                      "mentions": [
                        "rodrigo_123"
                      ]
                    },
                    {
                      "id": 26,
                      "name": "Rodrigo Oliveira",
                      "username": "rodrigo_123",
                      "content": "this is a good comment @rodrigo_123",
                      "created_datetime": "2025-07-28T21:34:35.260028Z",
                      "mentions": [
                        "rodrigo_123"
                      ]
                    },
                    {
                      "id": 25,
                      "name": "Rodrigo Oliveira",
                      "username": "rodrigo_123",
                      "content": "this is a good comment @rodrigo_123",
                      "created_datetime": "2025-07-28T21:34:34.297644Z",
                      "mentions": [
                        "rodrigo_123"
                      ]
                    },
                    {
                      "id": 24,
                      "name": "Rodrigo Oliveira",
                      "username": "rodrigo_123",
                      "content": "this is a good comment @rodrigo_123",
                      "created_datetime": "2025-07-28T21:34:33.370942Z",
                      "mentions": [
                        "rodrigo_123"
                      ]
                    },
                    {
                      "id": 23,
                      "name": "Rodrigo Oliveira",
                      "username": "rodrigo_123",
                      "content": "this is a good comment @rodrigo_123",
                      "created_datetime": "2025-07-28T21:34:32.179269Z",
                      "mentions": [
                        "rodrigo_123"
                      ]
                    },
                    {
                      "id": 22,
                      "name": "Rodrigo Oliveira",
                      "username": "rodrigo_123",
                      "content": "this is a good comment @rodrigo_123",
                      "created_datetime": "2025-07-28T21:34:29.436872Z",
                      "mentions": [
                        "rodrigo_123"
                      ]
                    }
                  ]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "post": {
        "summary": "Comment",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "postId",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjZkZTQwZjA0ODgxYzZhMDE2MTFlYjI4NGE0Yzk1YTI1MWU5MTEyNTAiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiUm9kcmlnbyBPbGl2ZWlyYSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NLZjM5ZWJIOWRhZHJ2MU5IZGlQTTdjZGo3Qlh2UHk5TXJKZ3dzZnhxNk1PcDh2WUR2Wj1zOTYtYyIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb2RlbGVhcC1iYWNrZW5kLWMxMmRmIiwiYXVkIjoiY29kZWxlYXAtYmFja2VuZC1jMTJkZiIsImF1dGhfdGltZSI6MTc1MzY1NjM0MiwidXNlcl9pZCI6InRBZFEyb2o4VllOV05LWlp0YmIyVEQzWVU1cTEiLCJzdWIiOiJ0QWRRMm9qOFZZTldOS1padGJiMlREM1lVNXExIiwiaWF0IjoxNzUzNjU2MzQyLCJleHAiOjE3NTM2NTk5NDIsImVtYWlsIjoicm9kcmlnby5zaWx2YS5vbGl2ZWlyYTM2OUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJnb29nbGUuY29tIjpbIjExMTMyNTk2MzQ4NDA3MTQyMTUyMSJdLCJlbWFpbCI6WyJyb2RyaWdvLnNpbHZhLm9saXZlaXJhMzY5QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6Imdvb2dsZS5jb20ifX0.E7c-9buFzOKBNTbN5hIg1wU6pVFM9jEO90WO01OV4fjdGtzShVr42yWlI4EYK5oyahYHWTpMVs54sZ8k-FfjAEB6Mp3VBoS3ooPcJsg7_N6QQyim5vc_zKrN0MHQnuDZNRyTkaC4aKVtRyvA9gXf0S8Jw7MpBT-x1qDrMs35_PkKeQOG0isposVAKYCQCqwHmOtwIMt5LaWewtpmH1mvBsHQst4NeMbr6YpxDhG-SXt1G1YY7UKNJyHNAwlh-P6g5BIhyfKEwPAHgkuvWt2ywK2T5GBXW_UoU4rbAhO8feqJkIozRMrxWyuvSpSG3-n_uHnItlVxKklNoYuJ15v5gg",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "content": {
                    "type": "string"
                  }
                },
                "required": [
                  "content"
                ]
              },
              "example": {
                "content": "this is a good comment @rodrigo_123"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    },
                    "content": {
                      "type": "string"
                    },
                    "created_datetime": {
                      "type": "string"
                    },
                    "mentions": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  },
                  "required": [
                    "id",
                    "name",
                    "username",
                    "content",
                    "created_datetime",
                    "mentions"
                  ]
                },
                "example": {
                  "id": 27,
                  "name": "Rodrigo Oliveira",
                  "username": "rodrigo_123",
                  "content": "this is a good comment @rodrigo_123",
                  "created_datetime": "2025-07-28T21:34:36.317264Z",
                  "mentions": [
                    "rodrigo_123"
                  ]
                }
              }
            },
            "headers": {}
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "content": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  },
                  "required": [
                    "content"
                  ]
                },
                "example": {
                  "content": [
                    "This field is required."
                  ]
                }
              }
            },
            "headers": {}
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "detail": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "detail"
                  ]
                },
                "example": {
                  "detail": "Authentication credentials were not provided."
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/careers/{postId}/comments/{commentId}/": {
      "get": {
        "summary": "Comment",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "postId",
            "in": "path",
            "description": "",
            "required": true,
            "example": "3",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "commentId",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjZkZTQwZjA0ODgxYzZhMDE2MTFlYjI4NGE0Yzk1YTI1MWU5MTEyNTAiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiUm9kcmlnbyBPbGl2ZWlyYSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NLQ2I5VjBNMVBFN2VUZVpXT3YxRVBtMWpGWkNfaFgyQ256YXhHNTNYS3N6WFRRWlE9czk2LWMiLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29kZWxlYXAtYmFja2VuZC1jMTJkZiIsImF1ZCI6ImNvZGVsZWFwLWJhY2tlbmQtYzEyZGYiLCJhdXRoX3RpbWUiOjE3NTM2NjExOTgsInVzZXJfaWQiOiJFSUtDRGdVZ1dTWmVyZ2wxbFlZbnlyT2lvVFcyIiwic3ViIjoiRUlLQ0RnVWdXU1plcmdsMWxZWW55ck9pb1RXMiIsImlhdCI6MTc1MzY2MTE5OCwiZXhwIjoxNzUzNjY0Nzk4LCJlbWFpbCI6InJvZHJpZ28uc2lsdmEub2xpdmVpcmE5MzVAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZ29vZ2xlLmNvbSI6WyIxMTc2NDY0Mjk0Njk1ODc5ODc4NTUiXSwiZW1haWwiOlsicm9kcmlnby5zaWx2YS5vbGl2ZWlyYTkzNUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJnb29nbGUuY29tIn19.Kk1uQPlbjVxze_zmCsRfE8SNQptnIyq0C0rIee5BHeDUQ8_WrHj3UWOdIFoI8_aCMPEM9uW3gIv4rV7UBEyRhcHVHbdTIemr-k8YKvxVcKxhTLFfEwUIQMZ7m01laahyYuKfRNsl0VocAx2GOkZ4lUDav9T4DwCmgPz55HFeDoEZpL4uHyZTLTUJcRJCKVBIK03QoFbSKJsXOPmk0t7kRIEPqoqwylk7iRwJjMemVt4dN2W22hCnnjWktMxyEouQqzOQdIUGPtIK9fzAeGK5_iMNV4WtmfUOEr4wqjizwW_mnWgh1QwQWYsQmyRPPNyPccdStwZ_lJnLF6HexpAS2Q",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    },
                    "content": {
                      "type": "string"
                    },
                    "created_datetime": {
                      "type": "string"
                    },
                    "mentions": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  },
                  "required": [
                    "id",
                    "name",
                    "username",
                    "content",
                    "created_datetime",
                    "mentions"
                  ]
                },
                "example": {
                  "id": 27,
                  "name": "Rodrigo Oliveira",
                  "username": "rodrigo_123",
                  "content": "this is a good comment @rodrigo_123",
                  "created_datetime": "2025-07-28T21:34:36.317264Z",
                  "mentions": [
                    "rodrigo_123"
                  ]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "patch": {
        "summary": "Comment",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "postId",
            "in": "path",
            "description": "",
            "required": true,
            "example": "3",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "commentId",
            "in": "path",
            "description": "",
            "required": true,
            "example": "2",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjZkZTQwZjA0ODgxYzZhMDE2MTFlYjI4NGE0Yzk1YTI1MWU5MTEyNTAiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiUm9kcmlnbyBPbGl2ZWlyYSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NLZjM5ZWJIOWRhZHJ2MU5IZGlQTTdjZGo3Qlh2UHk5TXJKZ3dzZnhxNk1PcDh2WUR2Wj1zOTYtYyIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb2RlbGVhcC1iYWNrZW5kLWMxMmRmIiwiYXVkIjoiY29kZWxlYXAtYmFja2VuZC1jMTJkZiIsImF1dGhfdGltZSI6MTc1MzY1NjM0MiwidXNlcl9pZCI6InRBZFEyb2o4VllOV05LWlp0YmIyVEQzWVU1cTEiLCJzdWIiOiJ0QWRRMm9qOFZZTldOS1padGJiMlREM1lVNXExIiwiaWF0IjoxNzUzNjU2MzQyLCJleHAiOjE3NTM2NTk5NDIsImVtYWlsIjoicm9kcmlnby5zaWx2YS5vbGl2ZWlyYTM2OUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJnb29nbGUuY29tIjpbIjExMTMyNTk2MzQ4NDA3MTQyMTUyMSJdLCJlbWFpbCI6WyJyb2RyaWdvLnNpbHZhLm9saXZlaXJhMzY5QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6Imdvb2dsZS5jb20ifX0.E7c-9buFzOKBNTbN5hIg1wU6pVFM9jEO90WO01OV4fjdGtzShVr42yWlI4EYK5oyahYHWTpMVs54sZ8k-FfjAEB6Mp3VBoS3ooPcJsg7_N6QQyim5vc_zKrN0MHQnuDZNRyTkaC4aKVtRyvA9gXf0S8Jw7MpBT-x1qDrMs35_PkKeQOG0isposVAKYCQCqwHmOtwIMt5LaWewtpmH1mvBsHQst4NeMbr6YpxDhG-SXt1G1YY7UKNJyHNAwlh-P6g5BIhyfKEwPAHgkuvWt2ywK2T5GBXW_UoU4rbAhO8feqJkIozRMrxWyuvSpSG3-n_uHnItlVxKklNoYuJ15v5gg",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "content": {
                    "type": "string"
                  }
                },
                "required": [
                  "content"
                ]
              },
              "example": {
                "content": "this is a comment"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    },
                    "content": {
                      "type": "string"
                    },
                    "created_datetime": {
                      "type": "string"
                    },
                    "mentions": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  },
                  "required": [
                    "id",
                    "name",
                    "username",
                    "content",
                    "created_datetime",
                    "mentions"
                  ]
                },
                "example": {
                  "id": 27,
                  "name": "Rodrigo Oliveira",
                  "username": "rodrigo_123",
                  "content": "this is a comment",
                  "created_datetime": "2025-07-28T21:34:36.317264Z",
                  "mentions": []
                }
              }
            },
            "headers": {}
          },
          "403": {
            "description": "User trying to patch a comment from other user",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "detail": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "detail"
                  ]
                },
                "example": {
                  "detail": "You do not have permission to perform this action."
                }
              }
            },
            "headers": {}
          },
          "x-403:Forbidden": {
            "description": "No athentication Bearer",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "detail": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "detail"
                  ]
                },
                "example": {
                  "detail": "Authentication credentials were not provided."
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "delete": {
        "summary": "Comment",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "postId",
            "in": "path",
            "description": "",
            "required": true,
            "example": "3",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "commentId",
            "in": "path",
            "description": "",
            "required": true,
            "example": "2",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjZkZTQwZjA0ODgxYzZhMDE2MTFlYjI4NGE0Yzk1YTI1MWU5MTEyNTAiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiUm9kcmlnbyBPbGl2ZWlyYSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NLZjM5ZWJIOWRhZHJ2MU5IZGlQTTdjZGo3Qlh2UHk5TXJKZ3dzZnhxNk1PcDh2WUR2Wj1zOTYtYyIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb2RlbGVhcC1iYWNrZW5kLWMxMmRmIiwiYXVkIjoiY29kZWxlYXAtYmFja2VuZC1jMTJkZiIsImF1dGhfdGltZSI6MTc1MzY1NjM0MiwidXNlcl9pZCI6InRBZFEyb2o4VllOV05LWlp0YmIyVEQzWVU1cTEiLCJzdWIiOiJ0QWRRMm9qOFZZTldOS1padGJiMlREM1lVNXExIiwiaWF0IjoxNzUzNjU2MzQyLCJleHAiOjE3NTM2NTk5NDIsImVtYWlsIjoicm9kcmlnby5zaWx2YS5vbGl2ZWlyYTM2OUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJnb29nbGUuY29tIjpbIjExMTMyNTk2MzQ4NDA3MTQyMTUyMSJdLCJlbWFpbCI6WyJyb2RyaWdvLnNpbHZhLm9saXZlaXJhMzY5QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6Imdvb2dsZS5jb20ifX0.E7c-9buFzOKBNTbN5hIg1wU6pVFM9jEO90WO01OV4fjdGtzShVr42yWlI4EYK5oyahYHWTpMVs54sZ8k-FfjAEB6Mp3VBoS3ooPcJsg7_N6QQyim5vc_zKrN0MHQnuDZNRyTkaC4aKVtRyvA9gXf0S8Jw7MpBT-x1qDrMs35_PkKeQOG0isposVAKYCQCqwHmOtwIMt5LaWewtpmH1mvBsHQst4NeMbr6YpxDhG-SXt1G1YY7UKNJyHNAwlh-P6g5BIhyfKEwPAHgkuvWt2ywK2T5GBXW_UoU4rbAhO8feqJkIozRMrxWyuvSpSG3-n_uHnItlVxKklNoYuJ15v5gg",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "204": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          },
          "403": {
            "description": "User trying to delete a comment from other user",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "detail": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "detail"
                  ]
                },
                "example": {
                  "detail": "You do not have permission to perform this action."
                }
              }
            },
            "headers": {}
          },
          "x-403:Forbidden": {
            "description": "No athentication Bearer",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "detail": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "detail"
                  ]
                },
                "example": {
                  "detail": "Authentication credentials were not provided."
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/careers/{postId}/like/": {
      "post": {
        "summary": "Like-a-post",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "postId",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User gives a like in a post",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          },
          "204": {
            "description": "User removes a like in a post",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "detail": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "detail"
                  ]
                },
                "example": {
                  "detail": "Authentication credentials were not provided."
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/careers/profile/": {
      "patch": {
        "summary": "Profile",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjZkZTQwZjA0ODgxYzZhMDE2MTFlYjI4NGE0Yzk1YTI1MWU5MTEyNTAiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiUm9kcmlnbyBPbGl2ZWlyYSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NLQ2I5VjBNMVBFN2VUZVpXT3YxRVBtMWpGWkNfaFgyQ256YXhHNTNYS3N6WFRRWlE9czk2LWMiLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29kZWxlYXAtYmFja2VuZC1jMTJkZiIsImF1ZCI6ImNvZGVsZWFwLWJhY2tlbmQtYzEyZGYiLCJhdXRoX3RpbWUiOjE3NTM2NjExOTgsInVzZXJfaWQiOiJFSUtDRGdVZ1dTWmVyZ2wxbFlZbnlyT2lvVFcyIiwic3ViIjoiRUlLQ0RnVWdXU1plcmdsMWxZWW55ck9pb1RXMiIsImlhdCI6MTc1MzY2MTE5OCwiZXhwIjoxNzUzNjY0Nzk4LCJlbWFpbCI6InJvZHJpZ28uc2lsdmEub2xpdmVpcmE5MzVAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZ29vZ2xlLmNvbSI6WyIxMTc2NDY0Mjk0Njk1ODc5ODc4NTUiXSwiZW1haWwiOlsicm9kcmlnby5zaWx2YS5vbGl2ZWlyYTkzNUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJnb29nbGUuY29tIn19.Kk1uQPlbjVxze_zmCsRfE8SNQptnIyq0C0rIee5BHeDUQ8_WrHj3UWOdIFoI8_aCMPEM9uW3gIv4rV7UBEyRhcHVHbdTIemr-k8YKvxVcKxhTLFfEwUIQMZ7m01laahyYuKfRNsl0VocAx2GOkZ4lUDav9T4DwCmgPz55HFeDoEZpL4uHyZTLTUJcRJCKVBIK03QoFbSKJsXOPmk0t7kRIEPqoqwylk7iRwJjMemVt4dN2W22hCnnjWktMxyEouQqzOQdIUGPtIK9fzAeGK5_iMNV4WtmfUOEr4wqjizwW_mnWgh1QwQWYsQmyRPPNyPccdStwZ_lJnLF6HexpAS2Q",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "app_username": {
                    "type": "string"
                  }
                },
                "required": [
                  "app_username"
                ]
              },
              "example": {
                "app_username": "rodrigo_123"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "name and email get from firebase auth",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "app_username": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "name",
                    "email",
                    "app_username"
                  ]
                },
                "example": {
                  "name": "Rodrigo Oliveira",
                  "email": "rodrigo.silva.oliveira369@gmail.com",
                  "app_username": "rodrigo_123"
                }
              }
            },
            "headers": {
              "Authorization": {
                "example": "Bearer",
                "required": false,
                "description": "",
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "app_username": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      },
                      "description": "app_username with \" \". Ex: \"user user\""
                    }
                  },
                  "required": [
                    "app_username",
                    "01K19ETHKYGGXH4HPPJ83HM980"
                  ]
                },
                "example": {
                  "app_username": [
                    "O nome de usuário pode conter apenas letras, números e underscores (_)."
                  ]
                }
              }
            },
            "headers": {}
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "detail": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "detail"
                  ]
                },
                "example": {
                  "detail": "Authentication credentials were not provided."
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/careers/": {
      "get": {
        "summary": "Posts",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "author",
            "in": "query",
            "description": "filters posts from a author with id",
            "required": true,
            "example": 0,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "cursor",
            "in": "query",
            "description": "comes from pagination on the bopdy of the response (next and previous)",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "ordering",
            "in": "query",
            "description": "filter ordering (-comments_count, comments_count, -likes_count, likes_count, created_datetime, -created_datetime)",
            "required": true,
            "example": "-comments_count",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "next": null,
                  "previous": null,
                  "results": [],
                  "type": "string"
                },
                "example": {
                  "next": "http://localhost:8000/careers/?author=&cursor=cD0yMDI1LTA3LTI4KzAxJTNBMzglM0E1NC4wNTYzNTklMkIwMCUzQTAw&ordering=",
                  "previous": "http://localhost:8000/careers/?author=&cursor=cD0yMDI1LTA3LTI4KzAxJTNBMzglM0E1NC4wNTYzNTklMkIwMCUzQTAw&ordering=",
                  "results": []
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "post": {
        "summary": "Post",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "Obteined from the basic front end",
            "required": false,
            "example": "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjZkZTQwZjA0ODgxYzZhMDE2MTFlYjI4NGE0Yzk1YTI1MWU5MTEyNTAiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiUm9kcmlnbyBPbGl2ZWlyYSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NLZjM5ZWJIOWRhZHJ2MU5IZGlQTTdjZGo3Qlh2UHk5TXJKZ3dzZnhxNk1PcDh2WUR2Wj1zOTYtYyIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb2RlbGVhcC1iYWNrZW5kLWMxMmRmIiwiYXVkIjoiY29kZWxlYXAtYmFja2VuZC1jMTJkZiIsImF1dGhfdGltZSI6MTc1MzY1MjQ1MywidXNlcl9pZCI6InRBZFEyb2o4VllOV05LWlp0YmIyVEQzWVU1cTEiLCJzdWIiOiJ0QWRRMm9qOFZZTldOS1padGJiMlREM1lVNXExIiwiaWF0IjoxNzUzNjUyNDUzLCJleHAiOjE3NTM2NTYwNTMsImVtYWlsIjoicm9kcmlnby5zaWx2YS5vbGl2ZWlyYTM2OUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJnb29nbGUuY29tIjpbIjExMTMyNTk2MzQ4NDA3MTQyMTUyMSJdLCJlbWFpbCI6WyJyb2RyaWdvLnNpbHZhLm9saXZlaXJhMzY5QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6Imdvb2dsZS5jb20ifX0.E9E-r4DaQam2f4b_PhW7VHZB-cHnS-_GnXZywCsuhPiGuGwXORXorMjjl6YuZf0uHIP1Ou34F08fzmZ5ozpuCmLMVGwgCjUB7ZQC4PIWwCdmFDG-ynTyIc0JE3yYWJD925vCHkDb7T4ElUIzNQP3mzS8ceFMHLpkwri09Fq1hmTQ1YSwG7NAgM8kN17hsKJnSflypqT5dUvhUU2kiy3HQysz1HVos0QKjijQIyNz3py4EpSA-fzrcKmZ6NA_-MhMkc2vFtmcNVeNREnapF51ba_kFPMA5XARSvjSzYwFF2D898V94pJ6DFQF2VYL5rlwTo4DwLc2XM6vEum_9dAXeQ",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "content": {
                    "type": "string"
                  }
                },
                "required": [
                  "title",
                  "content"
                ],
                "title": "Rodrigo"
              },
              "example": {
                "title": "test",
                "content": "Mention to @Rodrigo_123654"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    },
                    "created_datetime": {
                      "type": "string"
                    },
                    "title": {
                      "type": "string"
                    },
                    "content": {
                      "type": "string"
                    },
                    "comments_count": {
                      "type": "integer"
                    },
                    "likes_count": {
                      "type": "integer"
                    },
                    "mentions": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  },
                  "required": [
                    "id",
                    "name",
                    "username",
                    "created_datetime",
                    "title",
                    "content",
                    "comments_count",
                    "likes_count",
                    "mentions"
                  ]
                },
                "example": {
                  "id": 33,
                  "name": "Rodrigo Oliveira",
                  "username": "Rodrigo_123654",
                  "created_datetime": "2025-07-28T21:01:00.020559Z",
                  "title": "titulo",
                  "content": "Mention to @Rodrigo_123654",
                  "comments_count": 0,
                  "likes_count": 0,
                  "mentions": [
                    "Rodrigo_123654"
                  ]
                }
              }
            },
            "headers": {
              "Authorization": {
                "example": "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjZkZTQwZjA0ODgxYzZhMDE2MTFlYjI4NGE0Yzk1YTI1MWU5MTEyNTAiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiUm9kcmlnbyBPbGl2ZWlyYSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NLZjM5ZWJIOWRhZHJ2MU5IZGlQTTdjZGo3Qlh2UHk5TXJKZ3dzZnhxNk1PcDh2WUR2Wj1zOTYtYyIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb2RlbGVhcC1iYWNrZW5kLWMxMmRmIiwiYXVkIjoiY29kZWxlYXAtYmFja2VuZC1jMTJkZiIsImF1dGhfdGltZSI6MTc1MzczNjA2OCwidXNlcl9pZCI6InRBZFEyb2o4VllOV05LWlp0YmIyVEQzWVU1cTEiLCJzdWIiOiJ0QWRRMm9qOFZZTldOS1padGJiMlREM1lVNXExIiwiaWF0IjoxNzUzNzM2MDY4LCJleHAiOjE3NTM3Mzk2NjgsImVtYWlsIjoicm9kcmlnby5zaWx2YS5vbGl2ZWlyYTM2OUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJnb29nbGUuY29tIjpbIjExMTMyNTk2MzQ4NDA3MTQyMTUyMSJdLCJlbWFpbCI6WyJyb2RyaWdvLnNpbHZhLm9saXZlaXJhMzY5QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6Imdvb2dsZS5jb20ifX0.Z3K6q4IoDfEk-k17kQsKcLmKQ9SW8uQcrauF5yHIfro28VzZ7lKxnytvCb2MeoKMZVO31yYAZ8AXY5QAuDMXgRebXeB67ROs7pjgpgcO8bwOHrGPpexuCiQGgAq5qlCfxPp-m5dAG4FNzRDcvwTlh-hBLIhDDI0GPDdUP_ozcZHXumULOukBexJ04hYaM-yjG8q1xwLdNSE8TAzz7j9clC1nRXoCKmyWExrb90b1cn8Cr2axxg9D_gYzS5v6ZqvPiI8moCD4d1G12wNdn95HY4uqQX68PO2I32FCRRgLelibFAyjC5zCJSMya7OSIJTVuLgLmPS6NNYNrlqkkwQOwg",
                "required": false,
                "description": "",
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "detail": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "detail"
                  ]
                },
                "example": {
                  "detail": "Authentication credentials were not provided."
                }
              }
            },
            "headers": {
              "Authorization": {
                "example": "",
                "required": false,
                "description": "No Bearer value",
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/careers/{postId}/": {
      "get": {
        "summary": "Post",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "postId",
            "in": "path",
            "description": "Id from the Post",
            "required": true,
            "example": 3,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "author",
            "in": "query",
            "description": "filters posts from a author with id",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "cursor",
            "in": "query",
            "description": "comes from pagination on the bopdy of the response (next and previous)",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "ordering",
            "in": "query",
            "description": "filter ordering ( created_datetime, -created_datetime)",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    },
                    "created_datetime": {
                      "type": "string"
                    },
                    "title": {
                      "type": "string"
                    },
                    "content": {
                      "type": "string"
                    },
                    "comments_count": {
                      "type": "integer"
                    },
                    "likes_count": {
                      "type": "integer"
                    },
                    "mentions": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  },
                  "required": [
                    "id",
                    "name",
                    "username",
                    "created_datetime",
                    "title",
                    "content",
                    "comments_count",
                    "likes_count",
                    "mentions"
                  ],
                  "title": "aqui tem um teste"
                },
                "example": {
                  "id": 35,
                  "name": "Rodrigo Oliveira",
                  "username": "Rodrigo_123654",
                  "created_datetime": "2025-07-28T21:18:29.529791Z",
                  "title": "titulo",
                  "content": "Mention to @Rodrigo_123654",
                  "comments_count": 0,
                  "likes_count": 0,
                  "mentions": [
                    "Rodrigo_123654"
                  ]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/careers/{postID}/": {
      "patch": {
        "summary": "Post",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "postID",
            "in": "path",
            "description": "",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjZkZTQwZjA0ODgxYzZhMDE2MTFlYjI4NGE0Yzk1YTI1MWU5MTEyNTAiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiUm9kcmlnbyBPbGl2ZWlyYSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NLZjM5ZWJIOWRhZHJ2MU5IZGlQTTdjZGo3Qlh2UHk5TXJKZ3dzZnhxNk1PcDh2WUR2Wj1zOTYtYyIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb2RlbGVhcC1iYWNrZW5kLWMxMmRmIiwiYXVkIjoiY29kZWxlYXAtYmFja2VuZC1jMTJkZiIsImF1dGhfdGltZSI6MTc1MzczNjA2OCwidXNlcl9pZCI6InRBZFEyb2o4VllOV05LWlp0YmIyVEQzWVU1cTEiLCJzdWIiOiJ0QWRRMm9qOFZZTldOS1padGJiMlREM1lVNXExIiwiaWF0IjoxNzUzNzM2MDY4LCJleHAiOjE3NTM3Mzk2NjgsImVtYWlsIjoicm9kcmlnby5zaWx2YS5vbGl2ZWlyYTM2OUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJnb29nbGUuY29tIjpbIjExMTMyNTk2MzQ4NDA3MTQyMTUyMSJdLCJlbWFpbCI6WyJyb2RyaWdvLnNpbHZhLm9saXZlaXJhMzY5QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6Imdvb2dsZS5jb20ifX0.Z3K6q4IoDfEk-k17kQsKcLmKQ9SW8uQcrauF5yHIfro28VzZ7lKxnytvCb2MeoKMZVO31yYAZ8AXY5QAuDMXgRebXeB67ROs7pjgpgcO8bwOHrGPpexuCiQGgAq5qlCfxPp-m5dAG4FNzRDcvwTlh-hBLIhDDI0GPDdUP_ozcZHXumULOukBexJ04hYaM-yjG8q1xwLdNSE8TAzz7j9clC1nRXoCKmyWExrb90b1cn8Cr2axxg9D_gYzS5v6ZqvPiI8moCD4d1G12wNdn95HY4uqQX68PO2I32FCRRgLelibFAyjC5zCJSMya7OSIJTVuLgLmPS6NNYNrlqkkwQOwg",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "content": {
                    "type": "string"
                  }
                },
                "required": [
                  "title",
                  "content"
                ]
              },
              "example": {
                "title": "test update",
                "content": "contente update no mention"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    },
                    "created_datetime": {
                      "type": "string"
                    },
                    "title": {
                      "type": "string"
                    },
                    "content": {
                      "type": "string"
                    },
                    "comments_count": {
                      "type": "integer"
                    },
                    "likes_count": {
                      "type": "integer"
                    },
                    "mentions": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  },
                  "required": [
                    "id",
                    "name",
                    "username",
                    "created_datetime",
                    "title",
                    "content",
                    "comments_count",
                    "likes_count",
                    "mentions"
                  ]
                },
                "example": {
                  "id": 33,
                  "name": "Rodrigo Oliveira",
                  "username": "Rodrigo_123654",
                  "created_datetime": "2025-07-28T21:01:00.020559Z",
                  "title": "test update",
                  "content": "contente update no mention",
                  "comments_count": 0,
                  "likes_count": 0,
                  "mentions": []
                }
              }
            },
            "headers": {}
          },
          "403": {
            "description": "Different user trying to patch posts from others",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "detail": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "detail"
                  ]
                },
                "example": {
                  "detail": "You do not have permission to perform this action."
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "delete": {
        "summary": "Post",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "postID",
            "in": "path",
            "description": "",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjZkZTQwZjA0ODgxYzZhMDE2MTFlYjI4NGE0Yzk1YTI1MWU5MTEyNTAiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiUm9kcmlnbyBPbGl2ZWlyYSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NLZjM5ZWJIOWRhZHJ2MU5IZGlQTTdjZGo3Qlh2UHk5TXJKZ3dzZnhxNk1PcDh2WUR2Wj1zOTYtYyIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb2RlbGVhcC1iYWNrZW5kLWMxMmRmIiwiYXVkIjoiY29kZWxlYXAtYmFja2VuZC1jMTJkZiIsImF1dGhfdGltZSI6MTc1MzczNjA2OCwidXNlcl9pZCI6InRBZFEyb2o4VllOV05LWlp0YmIyVEQzWVU1cTEiLCJzdWIiOiJ0QWRRMm9qOFZZTldOS1padGJiMlREM1lVNXExIiwiaWF0IjoxNzUzNzM2MDY4LCJleHAiOjE3NTM3Mzk2NjgsImVtYWlsIjoicm9kcmlnby5zaWx2YS5vbGl2ZWlyYTM2OUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJnb29nbGUuY29tIjpbIjExMTMyNTk2MzQ4NDA3MTQyMTUyMSJdLCJlbWFpbCI6WyJyb2RyaWdvLnNpbHZhLm9saXZlaXJhMzY5QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6Imdvb2dsZS5jb20ifX0.Z3K6q4IoDfEk-k17kQsKcLmKQ9SW8uQcrauF5yHIfro28VzZ7lKxnytvCb2MeoKMZVO31yYAZ8AXY5QAuDMXgRebXeB67ROs7pjgpgcO8bwOHrGPpexuCiQGgAq5qlCfxPp-m5dAG4FNzRDcvwTlh-hBLIhDDI0GPDdUP_ozcZHXumULOukBexJ04hYaM-yjG8q1xwLdNSE8TAzz7j9clC1nRXoCKmyWExrb90b1cn8Cr2axxg9D_gYzS5v6ZqvPiI8moCD4d1G12wNdn95HY4uqQX68PO2I32FCRRgLelibFAyjC5zCJSMya7OSIJTVuLgLmPS6NNYNrlqkkwQOwg",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "204": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          },
          "403": {
            "description": "Different user trying to delete posts from others",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "detail": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "detail"
                  ]
                },
                "example": {
                  "detail": "You do not have permission to perform this action."
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {}
  },
  "servers": [],
  "security": []
}